#!/usr/bin/env python3

import json
import os
import re
import urllib.request
import urllib.error
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(__file__))


def fetch(url: str, timeout: int = 15) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "readme-bot"})
    return urllib.request.urlopen(req, timeout=timeout).read().decode()


def fetch_json(url: str) -> object:
    return json.loads(fetch(url))


def get_languages() -> list[str]:
    repos = fetch_json("https://api.github.com/users/morawskidotmy/repos?per_page=100")
    langs: set[str] = set()
    for r in repos:
        try:
            langs.update(fetch_json(r["languages_url"]).keys())
        except Exception:
            pass
    return sorted(langs)


def get_newest_article() -> tuple[str, str]:
    try:
        md = fetch(
            "https://raw.githubusercontent.com/morawskidotmy/morawski.my/main/articles/articles.md"
        )
        links = re.findall(r"\[([^\]]+)\]\(([^)]+)\)", md)
        if links:
            return links[-1]
    except Exception:
        pass
    return ("(no articles yet)", "https://morawski.my")


SITES = {
    "morawski.my": "https://morawski.my",
    "red.morawski.my": "https://red.morawski.my",
    "bin.morawski.my": "https://bin.morawski.my",
}


def check_site(url: str) -> bool:
    for method in ("HEAD", "GET"):
        try:
            req = urllib.request.Request(url, method=method, headers={"User-Agent": "readme-bot"})
            code = urllib.request.urlopen(req, timeout=10).status
            if code < 400:
                return True
        except Exception:
            pass
    return False


def get_weather() -> str:
    try:
        data = fetch_json(
            "https://api.open-meteo.com/v1/forecast?latitude=54.35&longitude=18.65"
            "&current=temperature_2m,weathercode&timezone=Europe%2FWarsaw"
        )
        code = data["current"]["weathercode"]
        temp = data["current"]["temperature_2m"]
        desc = {
            0: "clear skies", 1: "mostly clear", 2: "partly cloudy", 3: "cloudy",
            45: "foggy", 48: "foggy", 51: "drizzly", 53: "drizzly", 55: "drizzly",
            61: "rainy", 63: "rainy", 65: "heavy rain", 71: "snowy", 73: "snowy",
            75: "heavy snow", 80: "rainy", 81: "rainy", 82: "stormy",
            95: "thunderstorm", 96: "hail", 99: "hail",
        }.get(code, "mysterious")
        return f"{desc} day ({temp}C)"
    except Exception:
        return "weather unknown"


def get_charity() -> tuple[str, str]:
    try:
        html = fetch("https://www.siepomaga.pl/zbiorki")
        links = re.findall(
            r'href="(/[a-z0-9][\w-]+)"[^>]*>.*?class="[^"]*title', html, re.S
        )
        if links:
            slug = links[0]
            return (slug.strip("/"), f"https://www.siepomaga.pl{slug}")
    except Exception:
        pass
    return ("siepomaga.pl", "https://www.siepomaga.pl/zbiorki")


def main() -> None:
    print(":: fetching data...")
    langs = get_languages()
    article_title, article_url = get_newest_article()
    statuses = {name: check_site(url) for name, url in SITES.items()}
    weather = get_weather()
    charity_name, charity_url = get_charity()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    status_rows = ""
    for name, up in statuses.items():
        icon = ":green_circle:" if up else ":red_circle:"
        status_rows += f"<tr><td>{name}</td><td>{icon}</td></tr>"

    tech_str = " ".join(f"`{l}`" for l in langs)

    readme = f"""\
<!-- AUTO-GENERATED by CI -- do not edit manually -->

<div align="center">
<a href="https://github.com/morawskidotmy/morawskidotmy"><img src="chise.gif" width="300"/></a>
<br/>
<b>resident of free city of gdansk, wanna be coder</b>
<br/><br/>
<img src="gif.gif" alt="support trans rights" width="300"/>
</div>

---

<table>
<tr>
<td valign="top" width="33%">

**services**

| site | up? |
|------|-----|
{"".join(f"| {name} | {':green_circle:' if up else ':red_circle:'} |{chr(10)}" for name, up in statuses.items())}
</td>
<td valign="top" width="33%">

**gdansk weather rn**

{weather}

**latest article**

[{article_title}]({article_url})

</td>
<td valign="top" width="34%">

**charity spotlight**

if you find something i made useful consider donating:

[![siepomaga](https://www.siepomaga.pl/images/logo-short.svg)]({charity_url})
[{charity_name}]({charity_url})

</td>
</tr>
</table>

---

<div align="center">

{tech_str}

</div>

<sub>last updated: {now}</sub>
"""

    out = os.path.join(ROOT, "README.md")
    with open(out, "w") as f:
        f.write(readme)
    print(f":: wrote {out}")


if __name__ == "__main__":
    main()
